// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-central-1",
  aws_content_delivery_bucket: "contacts-20180831172932--hostingbucket",
  aws_content_delivery_bucket_region: "eu-central-1",
  aws_content_delivery_url: "https://d340668e44hrd1.cloudfront.net",
  aws_cognito_identity_pool_id:
    "eu-central-1:31394830-9e7b-40b8-8216-9e9a98eaa277",
  aws_cognito_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_T8Y1DNf0k",
  aws_user_pools_web_client_id: "nkqs98avtj6tq43ai8r21dtem"
};

export default awsmobile;
